# Common configuration shared between all applications
configserver:
  name: Docker JHipster Registry
  status: Connected to the JHipster Registry running in Docker

jhipster:
  security:
    authentication:
      jwt:
        # secret key which should be base64 encoded and changed in production
        base64-secret: OGExNDNjN2VkN2RhZmVhZTllNzYyNTQxN2QyNGNhMjk4NTUyOTVhODMxNjVhN2NlYjdjY2U1NTI0YTkyNjljZjA2OTJlNDhkODZhMGViMzdhZjIyODlhZGYzZjk1ZWM2ZmUyMWExODFkNTRjZmJiYmEwNDY3OGExZmE0NjQxMGE=

eureka:
  client:
    service-url:
      defaultZone: http://admin:${jhipster.registry.password}@localhost:8761/eureka/
